### ISSUE TITLE
Publish to clojars

### ISSUE THREAD

**Issue by abishek** [28/clj-pnm#1]
Can this be published to clojars or other such maven repo? Thanks!

**Comment by 28** [comment]
Hi @abishek,
I am in fact working on it. I will let you know when it is published.
Cannot give the ETA though. :-)

Cheers

**Comment by abishek** [comment]
Thanks @28. I was trying to use lein-git-down to workaround this. Turns out, for some reason, the plugin thinks github urls cannot start with a number. I guess I should report it there. I've forked just to get around this. I can try to look how to publish to clojars or other such repo and submit a PR if that'll help. Thanks anyway :-)

**Comment by 28** [comment]
Interesting find on lein-git-down... :-)

I never say no to a PR, but I'm working on publishing to Clojars on some other project so clj-pnm will tag along asap. :-D

**Comment by 28** [comment]
Well, the first release was pushed to Clojars: https://clojars.org/org.theparanoidtimes/clj-pnm/versions/0.1.0

Give it a try.

Cheers
